services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  pg_admin:
    image: dpage/pgadmin4  
    environment:
      PGADMIN_DEFAULT_EMAIL: user@ru.ru
      PGADMIN_DEFAULT_PASSWORD: user
    ports:
      - 80:80   